# Generated by Django 5.0.1 on 2024-02-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_basketitem_is_ordered_placed_basketitem_size_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='is_ordered_placed',
            field=models.BooleanField(default=False),
        ),
    ]
